prop-prefix:
  webpage: 'http://'
  blog: 'http://'
  twitter: 'https://twitter.com/'
  linkedin: 'http://linkedin/in/'
  facebook: 'https://www.facebook.com/'
  github: 'https://github.com/'
  gplus: 'https://plus.google.com/'
type-image:
  keyword: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/key.svg'
  community: 'https://use.fontawesome.com/releases/v5.0.8/svgs/regular/heart.svg'
  organisation: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/globe.svg'
  business: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/dollar-sign.svg'
  university: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/university.svg'
  person: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/user.svg'
  event: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/thumbtack.svg'
  project: ''
  report: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/cube.svg'
  tool: 'https://use.fontawesome.com/releases/v5.0.8/svgs/solid/wrench.svg'